org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neo_version=21.1.248
mod_id=cchq_soundphysics_compat
mod_name=CC:HQ Sound Physics Compat
mod_license=MIT
mod_version=0.1.0-beta11-hotfix3
mod_group_id=dev.cchqphysics.compat
