from pathlib import Path

p = Path('src/main/java/dev/cchqphysics/compat/audio/Beta9Optimizer.java')
text = p.read_text(encoding='utf-8')

old = '''        Vec3 reflected = result.reflectedWrite();\n        boolean haveReflected = reflected != null;\n        double rx = haveReflected ? reflected.x : Double.NaN;\n        double ry = haveReflected ? reflected.y : Double.NaN;\n        double rz = haveReflected ? reflected.z : Double.NaN;\n        float wetEnergy = maxAbs(result.r0(), result.r1(), result.r2(), result.r3());'''
new = '''        double rx = Double.NaN;\n        double ry = Double.NaN;\n        double rz = Double.NaN;\n        boolean haveReflected = false;\n        try {\n            Object reflected = result.reflectedWrite();\n            if (reflected != null) {\n                var xField = reflected.getClass().getField("x");\n                var yField = reflected.getClass().getField("y");\n                var zField = reflected.getClass().getField("z");\n                rx = ((Number) xField.get(reflected)).doubleValue();\n                ry = ((Number) yField.get(reflected)).doubleValue();\n                rz = ((Number) zField.get(reflected)).doubleValue();\n                haveReflected = true;\n            }\n        } catch (Throwable ignored) {\n        }\n        float wetEnergy = maxAbs(result.r0(), result.r1(), result.r2(), result.r3());'''
if text.count(old) != 1:
    raise SystemExit(f'observeRoom block count={text.count(old)}')
text = text.replace(old, new, 1)

start = text.index('    private static void maybeReportAndControl(long now) {')
end = text.index('    static synchronized double adaptiveFactorForTest()', start)
replacement = '''    private static void maybeReportAndControl(long now) {\n        updateController(now);\n        long elapsed = now - reportStartNs;\n        if (elapsed < REPORT_NS) return;\n        double seconds = elapsed / 1.0E9D;\n        String report = "[CC:HQ Sound Physics Compat] beta9 extra window=" + round1(seconds)\n                + "s directReal=" + directReal + " (" + round1(directReal / seconds) + "/s)"\n                + " directReuses=" + directReuse + " (" + round1(directReuse / seconds) + "/s)"\n                + " directAvg=" + avgMs(directTotalNs, directReal + directReuse) + "ms"\n                + " directMax=" + ms(directMaxNs) + "ms"\n                + " realAgeAvg=" + avgMs(directRealAgeTotalNs, directRealAgeSamples) + "ms"\n                + " realAgeMax=" + ms(directRealAgeMaxNs) + "ms"\n                + " validateGapAvg=" + avgMs(directValidationGapTotalNs, directValidationSamples) + "ms"\n                + " validateGapMax=" + ms(directValidationGapMaxNs) + "ms"\n                + " sentinelAvg=" + avgMs(sentinelTotalNs, sentinelCalls) + "ms"\n                + " sentinelMax=" + ms(sentinelMaxNs) + "ms"\n                + " efxAvg=" + avgMs(efxTotalNs, efxPasses) + "ms"\n                + " efxMax=" + ms(efxMaxNs) + "ms"\n                + " inaudibleSkips=" + inaudibleSkips\n                + " stableBackoffs=" + stableBackoffs\n                + " relevanceBackoffs=" + relevanceBackoffs\n                + " adaptiveBackoffs=" + adaptiveBackoffs\n                + " movementResets=" + movementResets\n                + " roomStable=" + roomStableObservations + "/" + roomObservations\n                + " loadFactor=" + round2(adaptiveFactor)\n                + " loadRange=" + round2(reportMinAdaptive) + "-" + round2(reportMaxAdaptive)\n                + " acoustic=" + round1(lastAcousticMsPerSec) + "ms/s"\n                + " sprLoad=" + round1(lastSprMsPerSec) + "ms/s"\n                + " qCtrlAvg=" + round3(lastQueueAvgMs) + "ms"\n                + " qCtrlMax=" + round3(lastQueueMaxMs) + "ms"\n                + " ctrlUp=" + controllerUps + " ctrlDown=" + controllerDowns;\n        SoundPhysicsBridge.beta9Log(report);\n\n        reportStartNs = now;\n        directReal = directReuse = directTotalNs = directMaxNs = 0L;\n        directRealAgeSamples = directRealAgeTotalNs = directRealAgeMaxNs = 0L;\n        directValidationSamples = directValidationGapTotalNs = directValidationGapMaxNs = 0L;\n        sentinelCalls = sentinelTotalNs = sentinelMaxNs = 0L;\n        efxPasses = efxTotalNs = efxMaxNs = 0L;\n        inaudibleSkips = stableBackoffs = relevanceBackoffs = adaptiveBackoffs = 0L;\n        movementResets = roomStableObservations = roomObservations = 0L;\n        controllerUps = controllerDowns = 0L;\n        reportMinAdaptive = reportMaxAdaptive = adaptiveFactor;\n    }\n\n'''
text = text[:start] + replacement + text[end:]

text = text.replace('''    private static String avgMs(long ns, long count) {\n        return count <= 0L ? "0.000ms" : round3((ns / 1_000_000.0D) / count) + "ms";\n    }\n    private static String ms(long ns) { return round3(ns / 1_000_000.0D) + "ms"; }''', '''    private static String avgMs(long ns, long count) {\n        return count <= 0L ? "0.000" : String.format(Locale.ROOT, "%.3f", (ns / 1_000_000.0D) / count);\n    }\n    private static String ms(long ns) { return String.format(Locale.ROOT, "%.3f", ns / 1_000_000.0D); }''', 1)

p.write_text(text, encoding='utf-8')
print('Beta9 Hotfix3 semantics aligned')
